site_name: Mandarin Architecture
site_url: https://hans-blok.github.io/mandarin-architecture/
repo_url: https://github.com/hans-blok/mandarin-architecture
edit_uri: edit/main/docs/

theme:
  name: material
  language: nl
  logo: assets/mandarin-logo-m.png
  favicon: assets/mandarin-logo-m.png
  logo_link: /
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate

# extra_css:
#   - style/mandarin.css

plugins:
  - search

nav:
  - Home: index.md
  - Organisatie-Principes: organisatie-principes.md
  - Toelichting Mandarin: toelichting-mandarin.md
  - Concepten-in-Notendop:
      - Mandarin Artefacten in een Notendop: mandarin-artefacten-in-een-notendop.md
      - Mandarin Agents in een Notendop: mandarin-agents-in-een-notendop.md
  - Concepten:
      - Domeinconcepten: mandarin-domeinconcepten.md
      - Ordeningsconcepten: mandarin-ordeningsconcepten.md
      - Value Streams en Fasen: mandarin-value-streams-en-fasen.md
      - Conceptuele Grondslagen: conceptuele-grondslagen.md
  - Essays:
      - De AS bestaat al: essay.de-as-bestaat-al.md
      - Speckit pattern vs State pattern: essay.speckit-pattern-vs-state-pattern.md
  - Canon:
      - Axioma van gezag: axioma-van-gezag.md
      - Constitutie: constitutie.md
  
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
